site_name: How2KobraGoNeo
site_description: Tips, tweaks and mods for Anycubic Kobra Go and Neo.
site_author: Ulf Dieckmann
site_url: https://1coderookie.github.io/How2KobraGoNeo/
nav: 
    - Home: 'index.md'
    - The Printers: 'printers.md'
    - Hardware:
        - The Printhead: 
            - Printhead: 'printhead.md'
            - Extruder: 'extruder.md'
            - Hotend: 'hotend.md'
            - Nozzle: 'nozzle.md'
            - Silicone Sock: 'siliconesock.md'
            - Mods: 'mods_head.md'
        - The Mainboard: 
            - TriGorilla (Stock): 'mainboard_stock.md'
            - SKR3 (Mod): 'mainboard_skr3.md'
    - Firmware:
        - Marlin (Stock): 'fw_marlin.md'
        - Klipper (Mod): 'fw_klipper.md'


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
#    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  plugins:
    - search:
         lang: en
         separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    
